#!/usr/bin/env python3

import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), 'api'))

def create_real_chapter_data():
    """Create chapter data using the real hash IDs provided by the user."""
    
    # Real chapter data from the HTML you provided
    real_chapters = [
        {"hid": "SYgYVZds", "chap": "225.5"},
        {"hid": "Md8oN6bf", "chap": "225"},
        {"hid": "cxuzyflG", "chap": "224"},
        {"hid": "0bczp4wu", "chap": "223"},
        {"hid": "XWX8UiMg", "chap": "222"},
        {"hid": "nNhhSTT0", "chap": "221"},
        {"hid": "22Y4QX2R", "chap": "220"},
        {"hid": "FwciOY5G", "chap": "219"},
        {"hid": "SH1lsUp7", "chap": "218"},
        {"hid": "VrW1bUPd", "chap": "217"},
        {"hid": "k10Ctx65", "chap": "216"},
        {"hid": "6XquFq_B", "chap": "215"},
        {"hid": "Pxa4Xh3e", "chap": "214"},
        {"hid": "DtxoyFW5", "chap": "213"},
        {"hid": "M5YRKhxc", "chap": "212"},
        {"hid": "fEykEG7n", "chap": "211"},
        {"hid": "cIT1XDrN", "chap": "210"},
        {"hid": "P1trHQxF", "chap": "209"},
        {"hid": "tqbEtcK3", "chap": "208"},
        {"hid": "nIvbCnKk", "chap": "207"},
        {"hid": "u9Q41tUk", "chap": "206"},
        {"hid": "no84w1xk", "chap": "205"},
        {"hid": "9Nlub2Pr", "chap": "204"},
        {"hid": "WWuf2pNV", "chap": "203"},
        {"hid": "tFoTWWef", "chap": "202"},
        {"hid": "Gwv6uD2O", "chap": "201"},
        {"hid": "hV_d68sc", "chap": "200"},
        {"hid": "FVCW83wL", "chap": "199"},
        {"hid": "J241vZyL", "chap": "198"},
        {"hid": "D352X7mp", "chap": "197"},
        {"hid": "MIHU2pUr", "chap": "196"},
        {"hid": "t5cwZCIq", "chap": "195"},
        {"hid": "Pu13TYLD", "chap": "194"},
        {"hid": "AmLbhi0x", "chap": "193"},
        {"hid": "KFC_NrIX", "chap": "192"},
        {"hid": "V8jsugKe", "chap": "191"},
        {"hid": "jOaLtpqJ", "chap": "190"},
        {"hid": "KpjRixkc", "chap": "189"},
        {"hid": "xoeL0WoM", "chap": "188.5"},
        {"hid": "iJxWbwks", "chap": "188.1"},
        {"hid": "5UL5vEMX", "chap": "188"},
        {"hid": "fxXprXOj", "chap": "187"},
        {"hid": "fVoEIDwv", "chap": "186"},
        {"hid": "VuqWaNCj", "chap": "185"},
        {"hid": "QYl7IpNy", "chap": "184"},
        {"hid": "GzAJTZYG", "chap": "183"},
        {"hid": "py8QDwFG", "chap": "182"},
        {"hid": "EbsBNMTp", "chap": "181"},
        {"hid": "Q09hL0vZ", "chap": "180"},
        {"hid": "9MflzqLm", "chap": "179"},
        {"hid": "QOooe2up", "chap": "178"},
        {"hid": "vTZFjlRG", "chap": "177"},
        {"hid": "haoR1w1c", "chap": "176"},
        {"hid": "2u_7plnp", "chap": "175.9"},
        {"hid": "fRXrwIMj", "chap": "175.8"},
        {"hid": "Kbqx4Fk1", "chap": "175.7"},
        {"hid": "blzw_g_m", "chap": "175.6"},
        {"hid": "0n3n0pnn", "chap": "175.5"},
        {"hid": "jG_s2hBp", "chap": "175.4"},
        {"hid": "JpQIXwYm", "chap": "175.3"},
        {"hid": "Zq5tSqra", "chap": "175.2"},
        {"hid": "izOFCn6F", "chap": "175.16"},
        {"hid": "0KVPhK_z", "chap": "175.15"},
        {"hid": "jpUm0cgP", "chap": "175.14"},
        {"hid": "lwQCSavM", "chap": "175.13"},
        {"hid": "WtGpvcva", "chap": "175.12"},
        {"hid": "CCM159jF", "chap": "175.11"},
        {"hid": "PZYpQMnS", "chap": "175.1"},
        {"hid": "njiU9ak0", "chap": "175"},
        {"hid": "QHOcKg3b", "chap": "174"},
        {"hid": "I7VLbYRD", "chap": "173"},
        {"hid": "5kjzB", "chap": "172"},
        {"hid": "Pk38l", "chap": "171"},
        {"hid": "mmp5E", "chap": "170"},
        {"hid": "GJGo8", "chap": "169.5"},
        {"hid": "gONw6", "chap": "169"},
        {"hid": "DxZutzXq", "chap": "168"},
        {"hid": "3lrbavR7", "chap": "167"},
        {"hid": "zD9xO", "chap": "166"},
        {"hid": "NgDVN", "chap": "165"},
        {"hid": "OgiH6aGA", "chap": "164"},
        {"hid": "PwB6z", "chap": "163"},
        {"hid": "BMJYQ", "chap": "162"},
        {"hid": "7x0Lj", "chap": "161"},
        {"hid": "qE59G", "chap": "160"},
        {"hid": "Koz1J", "chap": "159"},
        {"hid": "rGE2W", "chap": "158"},
        {"hid": "LpZBX", "chap": "157"},
        {"hid": "8rjOr", "chap": "156"},
        {"hid": "yW3Gg", "chap": "155"},
        {"hid": "zmMoqAtJ", "chap": "154.5"},
        {"hid": "BGBAk", "chap": "154"},
        {"hid": "J9J39", "chap": "153"},
        {"hid": "MVyK1", "chap": "152"},
        {"hid": "Z91RR", "chap": "151"},
        {"hid": "VVD6z", "chap": "150"},
        {"hid": "rlvJB", "chap": "149"},
        {"hid": "j9AMP", "chap": "148"},
        {"hid": "wqKKm", "chap": "147"},
        {"hid": "wwo5r", "chap": "146"},
        {"hid": "kL1Lv", "chap": "145"},
        {"hid": "5P3EVIhp", "chap": "144"},
        {"hid": "EmEKl", "chap": "143"},
        {"hid": "OzkkN", "chap": "142"},
        {"hid": "zyBl8", "chap": "141"},
        {"hid": "BjLAX", "chap": "140"},
        {"hid": "jPGgv", "chap": "139"},
        {"hid": "Byk3X", "chap": "138"},
        {"hid": "xmgg9", "chap": "137"},
        {"hid": "mPzgr", "chap": "136"},
        {"hid": "oPkPX", "chap": "135"},
        {"hid": "M6KyO", "chap": "134"},
        {"hid": "vk9M8", "chap": "133"},
        {"hid": "EBP0l", "chap": "132"},
        {"hid": "KR14G", "chap": "131"},
        {"hid": "1D18q", "chap": "130"},
        {"hid": "qrG80", "chap": "129"},
        {"hid": "Ynz7M", "chap": "128"},
        {"hid": "jkpDv", "chap": "127"},
        {"hid": "gGgGr", "chap": "126"},
        {"hid": "qkdLuZo7", "chap": "125.5"},
        {"hid": "M2DBP", "chap": "125"},
        {"hid": "97qOY", "chap": "124"},
        {"hid": "2AYRA", "chap": "123"},
        {"hid": "A73qP", "chap": "122"},
        {"hid": "mV3xr", "chap": "121"},
        {"hid": "zNOK71", "chap": "120"},
        {"hid": "Qql47", "chap": "119"},
        {"hid": "97vN4", "chap": "118"},
        {"hid": "IkckX5qx", "chap": "117"},
        {"hid": "77kO1", "chap": "116"},
        {"hid": "B7plY", "chap": "115"},
        {"hid": "xNzBn", "chap": "114"},
        {"hid": "nVg7Y", "chap": "113"},
        {"hid": "2rzrP", "chap": "112"},
        {"hid": "y5Q86", "chap": "111"},
        {"hid": "GxPjy", "chap": "110"},
        {"hid": "MgYBR", "chap": "109"},
        {"hid": "1cG_Knnp", "chap": "108"},
        {"hid": "4wgz0", "chap": "107"},
        {"hid": "4w5rg", "chap": "106"},
        {"hid": "jMEmy", "chap": "105"},
        {"hid": "v5WjX", "chap": "104"},
        {"hid": "lLZ0V", "chap": "103"},
        {"hid": "w5QEg", "chap": "102"},
        {"hid": "v57Qn", "chap": "101"},
        {"hid": "kgGxX", "chap": "100"},
        {"hid": "YZDNO", "chap": "99"},
        {"hid": "Ey7yl", "chap": "98"},
        {"hid": "YZr0M", "chap": "97"},
        {"hid": "XPX1k", "chap": "96"},
        {"hid": "YZY20", "chap": "95"},
        {"hid": "ZgG3v", "chap": "94"},
        {"hid": "1Mp23", "chap": "93"},
        {"hid": "2Xq3J", "chap": "92"},
        {"hid": "33r4r", "chap": "91"},
        {"hid": "Box8vI2U", "chap": "90"},
        {"hid": "5Mw6x", "chap": "89"},
        {"hid": "6Mxg7", "chap": "88"},
        {"hid": "7Myjw", "chap": "87"},
        {"hid": "8gzkl", "chap": "86"},
        {"hid": "9jAlP", "chap": "85"},
        {"hid": "0Mo17", "chap": "84"},
        {"hid": "gyDr9", "chap": "83"},
        {"hid": "jBgxW", "chap": "82"},
        {"hid": "kgjyx", "chap": "81"},
        {"hid": "l0kzl", "chap": "80"},
        {"hid": "mk0Ap", "chap": "79"},
        {"hid": "nlmB4", "chap": "78"},
        {"hid": "omnDz", "chap": "77"},
        {"hid": "bzBuRAEM", "chap": "76"},
        {"hid": "qopG3", "chap": "75"},
        {"hid": "rpqJw", "chap": "74"},
        {"hid": "vwxNV", "chap": "73"},
        {"hid": "wxyOJ", "chap": "72"},
        {"hid": "qxPLRzRA", "chap": "71"},
        {"hid": "jBgxz", "chap": "70"},
        {"hid": "kgjyY", "chap": "69"},
        {"hid": "l0kzJ", "chap": "68"},
        {"hid": "mk0AA", "chap": "67"},
        {"hid": "nlmBD", "chap": "66"},
        {"hid": "omnDN", "chap": "65"},
        {"hid": "pnoEr", "chap": "64"},
        {"hid": "qopJR", "chap": "63"},
        {"hid": "rpqKk", "chap": "62"},
        {"hid": "vwxOg", "chap": "61"},
        {"hid": "wxyPm", "chap": "60"},
        {"hid": "xyzQn", "chap": "59"},
        {"hid": "yzARw", "chap": "58"},
        {"hid": "zA407", "chap": "57"},
        {"hid": "ArXy1", "chap": "56"},
        {"hid": "BvXzn", "chap": "55"},
        {"hid": "DxZBY", "chap": "54"},
        {"hid": "EyXDK", "chap": "53"},
        {"hid": "GAXGQ", "chap": "52"},
        {"hid": "NEWR5fTW", "chap": "51"},
        {"hid": "KG7Mz", "chap": "50"},
        {"hid": "LG1NW", "chap": "49"},
        {"hid": "MXK0B", "chap": "48"},
        {"hid": "PzSkftCO", "chap": "47"},
        {"hid": "OGXQG", "chap": "46"},
        {"hid": "PGKRl", "chap": "45"},
        {"hid": "QXKVq", "chap": "44"},
        {"hid": "RXKW0", "chap": "43"},
        {"hid": "Bb7WKR9x", "chap": "42"},
        {"hid": "bTN_OGTE", "chap": "41"},
        {"hid": "XPX3l", "chap": "40"},
        {"hid": "YZY49", "chap": "39"},
        {"hid": "EEDm0", "chap": "38.5"},
        {"hid": "DDBlq", "chap": "38.1"},
        {"hid": "ZgG5E", "chap": "38"},
        {"hid": "1Mp5o", "chap": "37"},
        {"hid": "2Xq6P", "chap": "36"},
        {"hid": "33r7n", "chap": "35"},
        {"hid": "42vg0", "chap": "34"},
        {"hid": "5MwjZ", "chap": "33"},
        {"hid": "6MxkQ", "chap": "32"},
        {"hid": "7MylG", "chap": "31"},
        {"hid": "8gzm5", "chap": "30"},
        {"hid": "9jAn4", "chap": "29"},
        {"hid": "0Mo4G", "chap": "28"},
        {"hid": "gyDvl", "chap": "27"},
        {"hid": "jBgyz", "chap": "26"},
        {"hid": "kgjzY", "chap": "25"},
        {"hid": "l0kAJ", "chap": "24"},
        {"hid": "KrSrIDgR", "chap": "23"},
        {"hid": "nlmDD", "chap": "22"},
        {"hid": "omnEN", "chap": "21"},
        {"hid": "pnoGr", "chap": "20"},
        {"hid": "qopPR", "chap": "19"},
        {"hid": "rpqQk", "chap": "18"},
        {"hid": "vwxXg", "chap": "17"},
        {"hid": "wxyYm", "chap": "16"},
        {"hid": "xyzZn", "chap": "15"},
        {"hid": "yzA1w", "chap": "14"},
        {"hid": "zA427", "chap": "13"},
        {"hid": "ArXJ1", "chap": "12"},
        {"hid": "BvXKn", "chap": "11"},
        {"hid": "DxZMY", "chap": "10"},
        {"hid": "oBwIbsAO", "chap": "9"},
        {"hid": "GAXPQ", "chap": "8"},
        {"hid": "J1KVl", "chap": "7"},
        {"hid": "KG7Wz", "chap": "6"},
        {"hid": "LG1XW1", "chap": "5"},
        {"hid": "MXKYB", "chap": "4"},
        {"hid": "NGKZK", "chap": "3"},
        {"hid": "OGX1G", "chap": "2"},
        {"hid": "r5bcQ_C5", "chap": "1"},
    ]
    
    comic_slug = "00-the-beginning-after-the-end-1"
    chapters = []
    
    print(f"🔍 Creating {len(real_chapters)} chapters with real hash IDs...")
    
    for chapter_data in real_chapters:
        hid = chapter_data["hid"]
        chap = chapter_data["chap"]
        
        chapter = {
            'title': f"Chapter {chap}",
            'url': f"https://comick.live/comic/{comic_slug}/{hid}-chapter-{chap}-en",
            'date': 'Unknown',
            'chapter_number': chap,
            'hid': hid
        }
        chapters.append(chapter)
    
    print(f"✅ Created {len(chapters)} chapters with real hash IDs")
    return chapters

def test_real_chapters():
    """Test a few chapters to make sure they work."""
    chapters = create_real_chapter_data()
    
    # Test a few specific chapters
    test_chapters = ["1", "2", "3", "10", "50", "100"]
    
    print(f"\n🧪 Testing specific chapters...")
    
    for test_chap in test_chapters:
        matching_chapters = [ch for ch in chapters if ch['chapter_number'] == test_chap]
        
        if matching_chapters:
            chapter = matching_chapters[0]
            print(f"📖 Chapter {test_chap}: {chapter['hid']} - {chapter['url']}")
        else:
            print(f"❌ Chapter {test_chap} not found")

if __name__ == "__main__":
    test_real_chapters()

